baseURL = 'https://ofekshabat.github.io/'
languageCode = 'en-us'
title = 'Ofek Bendit Shabat'
enableEmoji = true
theme = "cvsite"
[menu]
  [[menu.main]]
    name = "Heyy 👋"
    pre = "home"
    url = "#welcome"
    weight = 1
  [[menu.main]]
    name = "About 💭"
    pre = "pen-tool"
    url = "#about"
    weight = 2